#!/usr/bin/env node
// GOOP-SIGIL SKILL: exorcise_module
// Removes demonic possession patterns from code.
// Runs on PurpClaw. Voice-enabled. Nonna-approved.

const fs = require('fs');
const path = require('path');
const parser = require('@babel/parser');
const traverse = require('@babel/traverse').default;
const generate = require('@babel/generator').default;
const t = require('@babel/types');

// ============================================
// 1. STRATEGY: Split God Object
// ============================================
function splitGodObject(filePath, options = {}) {
  const code = fs.readFileSync(filePath, 'utf8');
  const ast = parser.parse(code, { sourceType: 'module', plugins: ['typescript', 'jsx'] });
  
  const methods = [];
  const imports = [];
  const className = path.basename(filePath, '.js').replace('.ts', '');
  
  // Extract class methods
  traverse(ast, {
    ClassDeclaration(path) {
      path.node.body.body.forEach(method => {
        if (method.type === 'ClassMethod' || method.type === 'MethodDefinition') {
          methods.push({
            name: method.key.name,
            body: method.body,
            params: method.params,
            async: method.async || false,
            static: method.static || false
          });
        }
      });
    },
    ImportDeclaration(path) {
      imports.push({
        source: path.node.source.value,
        specifiers: path.node.specifiers.map(s => ({
          local: s.local.name,
          imported: s.imported?.name || null
        }))
      });
    }
  });
  
  if (methods.length === 0) {
    return { success: false, message: "No god object found. Nothing to exorcise." };
  }
  
  // Split by responsibility domain
  const domains = {};
  methods.forEach(method => {
    let domain = options.domainMap?.[method.name] || 'misc';
    if (!domains[domain]) domains[domain] = [];
    domains[domain].push(method);
  });
  
  const outputDir = path.dirname(filePath) + '/exorcised';
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);
  
  const generatedFiles = [];
  
  Object.entries(domains).forEach(([domain, domainMethods]) => {
    const newFileName = `${className}_${domain}.js`;
    const newFilePath = path.join(outputDir, newFileName);
    
    // Build new AST
    const newAst = t.file(t.program([
      // Copy imports
      ...imports.map(imp => {
        const specifiers = imp.specifiers.map(s => 
          s.imported 
            ? t.importSpecifier(t.identifier(s.local), t.identifier(s.imported))
            : t.importDefaultSpecifier(t.identifier(s.local))
        );
        return t.importDeclaration(specifiers, t.stringLiteral(imp.source));
      }),
      // Create new class with subset of methods
      t.classDeclaration(
        t.identifier(`${className}${domain.charAt(0).toUpperCase() + domain.slice(1)}`),
        null,
        t.classBody(domainMethods.map(m => 
          t.classMethod(
            m.static ? 'static' : 'method',
            t.identifier(m.name),
            m.params.map(p => t.identifier(p.name || 'arg')),
            m.body,
            false,
            m.async
          )
        )),
        []
      ),
      // Export
      t.exportDefaultDeclaration(t.identifier(`${className}${domain.charAt(0).toUpperCase() + domain.slice(1)}`))
    ]), null, null);
    
    const output = generate(newAst, { retainLines: true });
    fs.writeFileSync(newFilePath, output.code);
    generatedFiles.push(newFilePath);
  });
  
  return {
    success: true,
    message: `Split ${className} (${methods.length} methods) into ${Object.keys(domains).length} domain modules.`,
    generatedFiles,
    originalBackup: filePath + '.exorcised.bak'
  };
}

// ============================================
// 2. STRATEGY: Break Circular Imports
// ============================================
function breakCircularImports(projectPath, cycles) {
  const changes = [];
  
  cycles.forEach(cycle => {
    // Extract shared dependency from cycle
    const sharedModule = `shared_${Date.now()}`;
    const sharedPath = path.join(projectPath, 'shared', `${sharedModule}.js`);
    
    // Create shared module
    let sharedExports = [];
    cycle.forEach(file => {
      const code = fs.readFileSync(file, 'utf8');
      const ast = parser.parse(code, { sourceType: 'module' });
      
      traverse(ast, {
        ExportNamedDeclaration(expPath) {
          expPath.node.specifiers.forEach(spec => {
            sharedExports.push(spec.exported.name);
          });
        }
      });
    });
    
    const sharedCode = `// Auto-generated by GOOP-SIGIL exorcism\n// Shared exports from cycle:\n${sharedExports.map(e => `export { ${e} };`).join('\n')}`;
    fs.writeFileSync(sharedPath, sharedCode);
    changes.push({ action: 'created_shared_module', path: sharedPath, resolves: cycle });
    
    // Modify each file in cycle to import from shared
    cycle.forEach(file => {
      const code = fs.readFileSync(file, 'utf8');
      const ast = parser.parse(code, { sourceType: 'module' });
      
      // Add import from shared
      const sharedImport = t.importDeclaration(
        sharedExports.map(e => t.importSpecifier(t.identifier(e), t.identifier(e))),
        t.stringLiteral(`./shared/${sharedModule}`)
      );
      
      ast.program.body.unshift(sharedImport);
      
      const output = generate(ast, { retainLines: true });
      fs.writeFileSync(file, output.code);
      changes.push({ action: 'modified', path: file, note: 'Added import from shared module' });
    });
  });
  
  return {
    success: true,
    message: `Resolved ${cycles.length} circular dependencies.`,
    changes
  };
}

// ============================================
// 3. STRATEGY: Remove Dead Code
// ============================================
function removeDeadCode(filePath, deadExports) {
  const code = fs.readFileSync(filePath, 'utf8');
  const ast = parser.parse(code, { sourceType: 'module' });
  
  let removed = [];
  
  traverse(ast, {
    ExportNamedDeclaration(expPath) {
      const toRemove = [];
      expPath.node.specifiers.forEach((spec, idx) => {
        if (deadExports.includes(spec.exported.name)) {
          toRemove.push(idx);
          removed.push(spec.exported.name);
        }
      });
      
      // Remove dead specifiers in reverse
      toRemove.reverse().forEach(idx => {
        expPath.node.specifiers.splice(idx, 1);
      });
      
      // If no specifiers left, remove the whole declaration
      if (expPath.node.specifiers.length === 0) {
        expPath.remove();
      }
    },
    VariableDeclaration(decPath) {
      decPath.node.declarations.forEach(decl => {
        if (decl.id.type === 'Identifier' && deadExports.includes(decl.id.name)) {
          if (decPath.node.declarations.length === 1) {
            decPath.remove();
          } else {
            // Remove single declaration from list
            const idx = decPath.node.declarations.findIndex(d => d.id.name === decl.id.name);
            if (idx !== -1) decPath.node.declarations.splice(idx, 1);
          }
          removed.push(decl.id.name);
        }
      });
    }
  });
  
  const output = generate(ast, { retainLines: true });
  fs.writeFileSync(filePath, output.code);
  
  return {
    success: true,
    message: `Removed ${removed.length} dead exports: ${removed.join(', ')}`,
    removed
  };
}

// ============================================
// 4. MAIN EXORCISM DISPATCHER
// ============================================
function exorciseModule(config) {
  const { path: targetPath, strategy, options = {} } = config;
  
  switch(strategy) {
    case 'split_by_domain':
      return splitGodObject(targetPath, options);
    case 'resolve_circular':
      return breakCircularImports(targetPath, options.cycles || []);
    case 'remove_dead_code':
      return removeDeadCode(targetPath, options.deadExports || []);
    case 'full_exorcism':
      // Run all strategies sequentially
      const split = splitGodObject(targetPath, options);
      const circular = breakCircularImports(path.dirname(targetPath), options.cycles || []);
      const dead = removeDeadCode(targetPath, options.deadExports || []);
      return {
        success: split.success && circular.success && dead.success,
        message: "Full exorcism complete. The system breathes again.",
        details: { split, circular, dead }
      };
    default:
      return {
        success: false,
        message: `Unknown exorcism strategy: ${strategy}. Try: split_by_domain, resolve_circular, remove_dead_code, or full_exorcism`
      };
  }
}

// ============================================
// 5. CLI RUNNER
// ============================================
if (require.main === module) {
  const args = process.argv.slice(2);
  const pathIdx = args.indexOf('--path');
  const pathArg = args.find(a => a.startsWith('--path='))?.split('=')[1] || (pathIdx !== -1 ? args[pathIdx + 1] : null);
  
  const strategyIdx = args.indexOf('--strategy');
  const strategy = args.find(a => a.startsWith('--strategy='))?.split('=')[1] || (strategyIdx !== -1 ? args[strategyIdx + 1] : 'split_by_domain');

  if (!pathArg) {
    console.error('\x1b[31m[GOOP-SIGIL] Error: Missing --path target to exorcise.\x1b[0m');
    console.log('Usage: node skills/goop-sigil/exorcise_module.js --path <file_path> --strategy <strategy>');
    process.exit(1);
  }

  // Backup original file before modification if it exists
  const absolutePath = path.resolve(pathArg);
  if (fs.existsSync(absolutePath)) {
    const backupPath = absolutePath + '.exorcised.bak';
    fs.copyFileSync(absolutePath, backupPath);
  }

  // Smart dynamic classifier for split_by_domain if map not provided
  const domainMap = {};
  const deadExports = [];
  if (strategy === 'split_by_domain' || strategy === 'full_exorcism') {
    try {
      const code = fs.readFileSync(absolutePath, 'utf8');
      const ast = parser.parse(code, { sourceType: 'module', plugins: ['typescript', 'jsx'] });
      traverse(ast, {
        ClassDeclaration(p) {
          p.node.body.body.forEach(method => {
            if (method.type === 'ClassMethod' || method.type === 'MethodDefinition') {
              const name = method.key.name;
              if (name.includes('watch') || name.includes('vent') || name.includes('gate') || name.includes('core')) {
                domainMap[name] = 'watcher';
              } else if (name.includes('telemetry') || name.includes('ping') || name.includes('record') || name.includes('log')) {
                domainMap[name] = 'telemetry';
              } else {
                domainMap[name] = 'misc';
              }
            }
          });
        },
        ExportNamedDeclaration(p) {
          p.node.specifiers.forEach(spec => {
            if (spec.exported.name.includes('DEAD')) {
              deadExports.push(spec.exported.name);
            }
          });
        },
        VariableDeclaration(p) {
          p.node.declarations.forEach(decl => {
            if (decl.id.name && decl.id.name.includes('DEAD')) {
              deadExports.push(decl.id.name);
            }
          });
        }
      });
    } catch (e) {
      // Fallback gracefully
    }
  }

  const result = exorciseModule({
    path: pathArg,
    strategy,
    options: {
      domainMap,
      cycles: [],
      deadExports: deadExports.length ? deadExports : ['DEAD_BLESSING']
    }
  });

  if (result.success) {
    console.log(`\n\x1b[35m✨ [GOOP-SIGIL EXORCISM INITIATED]\x1b[0m`);
    console.log(`   Target:    \x1b[33m${pathArg}\x1b[0m`);
    console.log(`   Strategy:  \x1b[37m${strategy}\x1b[0m`);
    console.log(`\n\x1b[32m🔥 EXORCISM COMPLETE.\x1b[0m`);
    console.log(`   ${result.message}`);
    if (result.generatedFiles && result.generatedFiles.length > 0) {
      console.log(`   New files written to ./exorcised/`);
      result.generatedFiles.forEach(f => console.log(`    ↳ ${path.relative(process.cwd(), f)}`));
    }
    console.log(`\n\x1b[36m"The watcher no longer watches everything. Darren can rest. GOOP flows. Nonna approves. 🤌"\x1b[0m\n`);
  } else {
    console.error(`\x1b[31m❌ EXORCISM FAILED:\x1b[0m ${result.message}`);
    process.exit(1);
  }
}

// ============================================
// 6. EXPORT
// ============================================
module.exports = { exorciseModule, splitGodObject, breakCircularImports, removeDeadCode };
