'use strict';
const path=require('path'),crypto=require('crypto');const{DatabaseSync}=require('node:sqlite');
const DB=process.env.PURPCLAW_SESSION_DB||path.join(path.resolve(__dirname,'..'),'.purpclaw','state.db'),db=(require('fs').mkdirSync(path.dirname(DB),{recursive:true}),new DatabaseSync(DB));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;CREATE TABLE IF NOT EXISTS a2a_tasks(id TEXT PRIMARY KEY,context_id TEXT,session_id TEXT,status TEXT NOT NULL,task TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_a2a_context ON a2a_tasks(context_id,updated_at);`);
const uid=prefix=>`${prefix}-${crypto.randomUUID()}`,now=()=>new Date().toISOString(),terminal=new Set(['completed','failed','canceled','rejected']);
function textParts(value={}){return(value.parts||[]).map(part=>part.text??part.root?.text??'').filter(Boolean).join('\n');}
function attachmentParts(value={}){return(value.parts||[]).map(part=>part.file?.uri||part.fileWithUri?.uri).filter(Boolean);}
function makeMessage(role,text,contextId,taskId){return{messageId:uid('message'),role,parts:[{text:String(text||'')}],contextId,taskId};}
class A2ARuntime{
 constructor(gateway,options={}){this.gateway=gateway;this.name=options.name||'PURPCLAW';this.description=options.description||'Local-first governed agentic workstation and orchestration runtime';}
 card(baseUrl){return{name:this.name,description:this.description,url:`${String(baseUrl).replace(/\/$/,'')}/a2a`,version:'1.0.0',protocolVersion:'1.0',capabilities:{streaming:true,pushNotifications:false,extendedAgentCard:false},defaultInputModes:['text/plain','application/json'],defaultOutputModes:['text/plain','application/json'],skills:[{id:'purpclaw-agent',name:'PURPCLAW Agent',description:'Persistent tool-using agent with workflows, MCP, files and governed execution',tags:['agent','coding','workflow','mcp']}],securitySchemes:{}};}
 persist(task){const stamp=now();db.prepare(`INSERT INTO a2a_tasks VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET status=excluded.status,task=excluded.task,session_id=excluded.session_id,updated_at=excluded.updated_at`).run(task.id,task.contextId||null,task.sessionId||null,task.status.state,JSON.stringify(task),task.createdAt||stamp,stamp);return task;}
 get(taskId){const row=db.prepare('SELECT task FROM a2a_tasks WHERE id=?').get(taskId);return row?JSON.parse(row.task):null;}
 list(params={}){const clauses=[],values=[];if(params.contextId){clauses.push('context_id=?');values.push(params.contextId);}values.push(Math.max(1,Math.min(Number(params.pageSize)||50,200)));return db.prepare(`SELECT task FROM a2a_tasks${clauses.length?` WHERE ${clauses.join(' AND ')}`:''} ORDER BY updated_at DESC LIMIT ?`).all(...values).map(row=>JSON.parse(row.task));}
 create(params={}){const incoming=params.message||{},taskId=incoming.taskId||params.id||uid('task'),existing=this.get(taskId);if(existing&&terminal.has(existing.status.state))throw Object.assign(new Error(`task ${taskId} is terminal`),{code:-32004});const contextId=incoming.contextId||params.contextId||existing?.contextId||uid('context');return this.persist(existing||{id:taskId,contextId,sessionId:null,status:{state:'submitted',timestamp:now()},history:[],artifacts:[],createdAt:now()});}
 async send(params={}){const task=this.create(params),prompt=textParts(params.message),attachments=attachmentParts(params.message);if(!prompt&&!attachments.length)throw Object.assign(new Error('A2A message requires a text or file part'),{code:-32602});task.history.push(params.message);task.status={state:'working',timestamp:now()};this.persist(task);try{const result=await this.gateway.submit({prompt,attachments,session_id:task.sessionId||undefined,platform:'a2a',operator_initiated:false});task.sessionId=result.session_id;const reply=makeMessage('agent',result.message,task.contextId,task.id);task.history.push(reply);task.status={state:'completed',message:reply,timestamp:now()};return this.persist(task);}catch(error){task.status={state:'failed',message:makeMessage('agent',`Execution failed: ${error.message}`,task.contextId,task.id),timestamp:now()};this.persist(task);throw error;}}
 cancel(taskId){const task=this.get(taskId);if(!task)throw Object.assign(new Error(`task not found: ${taskId}`),{code:-32001});if(terminal.has(task.status.state))return task;if(task.sessionId)try{this.gateway.interrupt(task.sessionId);}catch{}task.status={state:'canceled',timestamp:now()};return this.persist(task);}
 async handle(method,params={}){switch(method){case'SendMessage':case'message/send':return this.send(params);case'GetTask':case'tasks/get':{const task=this.get(params.id);if(!task)throw Object.assign(new Error(`task not found: ${params.id}`),{code:-32001});if(params.historyLength>=0)task.history=task.history.slice(-params.historyLength);return task;}case'ListTasks':case'tasks/list':return{tasks:this.list(params)};case'CancelTask':case'tasks/cancel':return this.cancel(params.id);default:throw Object.assign(new Error(`unsupported A2A operation: ${method}`),{code:-32601});}}
 async stream(rpcId,params,res){const task=this.create(params),prompt=textParts(params.message),attachments=attachmentParts(params.message);if(!prompt&&!attachments.length)throw Object.assign(new Error('A2A message requires a text or file part'),{code:-32602});task.history.push(params.message);task.status={state:'working',timestamp:now()};this.persist(task);const write=result=>res.write(`data: ${JSON.stringify({jsonrpc:'2.0',id:rpcId,result})}\n\n`);write(task);const delta=payload=>write({taskId:task.id,contextId:task.contextId,status:{state:'working',message:makeMessage('agent',payload.delta||'',task.contextId,task.id),timestamp:now()}}),artifact=payload=>{const value={artifactId:payload.id||uid('artifact'),name:payload.name||'artifact',parts:[payload.path?{file:{uri:payload.path}}:{data:payload.content}],metadata:{kind:payload.kind}};task.artifacts.push(value);this.persist(task);write({taskId:task.id,contextId:task.contextId,artifact:value,append:false,lastChunk:true});};this.gateway.on?.('message.delta',delta);this.gateway.on?.('artifact.created',artifact);try{const result=await this.gateway.submit({prompt,attachments,session_id:task.sessionId||undefined,platform:'a2a',operator_initiated:false});task.sessionId=result.session_id;const reply=makeMessage('agent',result.message,task.contextId,task.id);task.history.push(reply);task.status={state:'completed',message:reply,timestamp:now()};this.persist(task);write({taskId:task.id,contextId:task.contextId,status:task.status});}catch(error){task.status={state:'failed',message:makeMessage('agent',error.message,task.contextId,task.id),timestamp:now()};this.persist(task);write({taskId:task.id,contextId:task.contextId,status:task.status});}finally{this.gateway.off?.('message.delta',delta);this.gateway.off?.('artifact.created',artifact);res.end();}}
}
module.exports={A2ARuntime,textParts,attachmentParts,makeMessage,DB};
