'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');const{DatabaseSync}=require('node:sqlite');
const DB=process.env.PURPCLAW_SESSION_DB||path.join(path.resolve(__dirname,'..'),'.purpclaw','state.db'),db=(require('fs').mkdirSync(path.dirname(DB),{recursive:true}),new DatabaseSync(DB));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS session_artifacts(
id TEXT PRIMARY KEY,session_id TEXT NOT NULL,name TEXT NOT NULL,path TEXT,mime TEXT,kind TEXT NOT NULL,size INTEGER,sha256 TEXT,content TEXT,source_tool TEXT,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_artifacts_session ON session_artifacts(session_id,created_at);`);
if(!db.prepare('PRAGMA table_info(session_artifacts)').all().some(column=>column.name==='version')){db.exec('ALTER TABLE session_artifacts ADD COLUMN version INTEGER');const counters=new Map(),update=db.prepare('UPDATE session_artifacts SET version=? WHERE id=?');for(const row of db.prepare('SELECT id,session_id,name FROM session_artifacts ORDER BY created_at,id').all()){const key=`${row.session_id}\0${row.name}`,value=(counters.get(key)||0)+1;counters.set(key,value);update.run(value,row.id);}}db.exec('CREATE UNIQUE INDEX IF NOT EXISTS idx_artifact_version ON session_artifacts(session_id,name,version);');
function parse(row){return row?{id:row.id,sessionId:row.session_id,name:row.name,version:row.version,path:row.path,mime:row.mime,kind:row.kind,size:row.size,sha256:row.sha256,content:row.content,sourceTool:row.source_tool,createdAt:row.created_at}:null;}
function register(input={}){if(!input.sessionId)throw new Error('artifact sessionId is required');let absolute=null,bytes=null,kind=input.kind||'text',name=input.name||'artifact';if(input.path){absolute=path.resolve(input.path);const stat=fs.statSync(absolute);if(!stat.isFile())throw new Error('artifact path is not a file');bytes=fs.readFileSync(absolute);name=input.name||path.basename(absolute);kind=input.kind||(/^image\//.test(input.mime||'')?'image':'file');}else bytes=Buffer.from(String(input.content||''));const sha256=crypto.createHash('sha256').update(bytes).digest('hex'),id=`artifact-${sha256.slice(0,16)}-${Date.now().toString(36)}`,now=new Date().toISOString(),content=absolute?null:String(input.content||'').slice(0,250000),version=Number(input.version)||Number(db.prepare('SELECT MAX(version) value FROM session_artifacts WHERE session_id=? AND name=?').get(input.sessionId,name)?.value||0)+1;db.prepare('INSERT INTO session_artifacts(id,session_id,name,path,mime,kind,size,sha256,content,source_tool,created_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,input.sessionId,name,absolute,input.mime||null,kind,bytes.length,sha256,content,input.sourceTool||null,now,version);return get(id);}
function get(id){return parse(db.prepare('SELECT * FROM session_artifacts WHERE id=?').get(id));}
function list(sessionId,limit=100){return db.prepare(`SELECT * FROM session_artifacts ${sessionId?'WHERE session_id=?':''} ORDER BY created_at DESC LIMIT ?`).all(...(sessionId?[sessionId,limit]:[limit])).map(parse);}
function version(sessionId,name,number){return parse(db.prepare('SELECT * FROM session_artifacts WHERE session_id=? AND name=? AND version=?').get(sessionId,name,number));}
function latest(sessionId,name){return parse(db.prepare('SELECT * FROM session_artifacts WHERE session_id=? AND name=? ORDER BY version DESC LIMIT 1').get(sessionId,name));}
function versions(sessionId,name){return db.prepare('SELECT * FROM session_artifacts WHERE session_id=? AND name=? ORDER BY version').all(sessionId,name).map(parse);}
function discover(value,{sessionId,cwd=process.cwd(),sourceTool}={}){const root=path.resolve(cwd),candidates=new Set();function walk(item,depth=0){if(depth>4||item==null)return;if(typeof item==='string'){const patterns=item.match(/[A-Za-z]:\\[^\r\n"'<>|]+|\/(?:[^\s"'<>|]+\/)*[^\s"'<>|]+/g)||[];for(const found of patterns)candidates.add(found.trim());return;}if(Array.isArray(item)){item.forEach(x=>walk(x,depth+1));return;}if(typeof item==='object')for(const [key,entry] of Object.entries(item)){if(['path','file','filePath','outputPath','artifactPath'].includes(key)&&typeof entry==='string')candidates.add(entry);else walk(entry,depth+1);}}
walk(value);const artifacts=[];for(const candidate of candidates){try{const absolute=path.resolve(candidate);if(!(absolute===root||absolute.startsWith(root+path.sep)))continue;if(fs.statSync(absolute).isFile())artifacts.push(register({sessionId,path:absolute,sourceTool}));}catch{}}return artifacts;}
module.exports={register,get,list,version,latest,versions,discover,DB};
