'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');const{DatabaseSync}=require('node:sqlite');
const DB=process.env.PURPCLAW_SESSION_DB||path.join(path.resolve(__dirname,'..'),'.purpclaw','state.db'),db=(require('fs').mkdirSync(path.dirname(DB),{recursive:true}),new DatabaseSync(DB));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS attachments(
id TEXT PRIMARY KEY,session_id TEXT,name TEXT NOT NULL,path TEXT NOT NULL,mime TEXT,kind TEXT NOT NULL,size INTEGER NOT NULL,sha256 TEXT NOT NULL,preview TEXT,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_attachments_session ON attachments(session_id,created_at);`);
const TEXT_EXT=new Set(['.txt','.md','.json','.js','.ts','.tsx','.jsx','.py','.css','.html','.csv','.yml','.yaml','.sql','.sh','.log','.xml','.toml','.ini','.env']);
function kindOf(file,mime=''){const ext=path.extname(file).toLowerCase();if(String(mime).startsWith('image/')||['.png','.jpg','.jpeg','.gif','.webp','.bmp'].includes(ext))return'image';if(String(mime).startsWith('text/')||TEXT_EXT.has(ext))return'text';return'binary';}
function parse(row){return row?{id:row.id,sessionId:row.session_id,name:row.name,path:row.path,mime:row.mime,kind:row.kind,size:row.size,sha256:row.sha256,preview:row.preview,createdAt:row.created_at}:null;}
function register(input={}){const absolute=path.resolve(String(input.path||''));const stat=fs.statSync(absolute);if(!stat.isFile())throw new Error('attachment path is not a file');if(stat.size>(Number(input.maxBytes)||50*1024*1024))throw new Error('attachment exceeds 50MB limit');const bytes=fs.readFileSync(absolute),kind=kindOf(absolute,input.mime),sha256=crypto.createHash('sha256').update(bytes).digest('hex'),id=`att-${sha256.slice(0,16)}-${Date.now().toString(36)}`,now=new Date().toISOString();const preview=kind==='text'?bytes.toString('utf8').slice(0,16000):null;db.prepare('INSERT INTO attachments VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,input.sessionId||null,input.name||path.basename(absolute),absolute,input.mime||null,kind,stat.size,sha256,preview,now);return get(id);}
function get(id){return parse(db.prepare('SELECT * FROM attachments WHERE id=?').get(id));}
function list(sessionId,limit=100){return db.prepare(`SELECT * FROM attachments ${sessionId?'WHERE session_id=?':''} ORDER BY created_at DESC LIMIT ?`).all(...(sessionId?[sessionId,limit]:[limit])).map(parse);}
function resolve(items=[],sessionId){return(items||[]).map(item=>{if(typeof item==='string'){const known=get(item);if(known)return known;return register({path:item,sessionId});}if(item?.id){const known=get(item.id);if(known)return known;}if(item?.path)return register({...item,sessionId:sessionId||item.sessionId});return null;}).filter(Boolean);}
function prompt(text,items=[]){if(!items.length)return String(text||'');const block=items.map(item=>`- ${item.name} [${item.kind}, ${item.size} bytes, sha256:${item.sha256}]\n  path: ${item.path}${item.preview?`\n  preview:\n${item.preview.slice(0,4000)}`:''}`).join('\n');return`${text}\n\n[ATTACHMENTS — inspect these files as needed]\n${block}`.trim();}
module.exports={register,get,list,resolve,prompt,kindOf,DB};
