'use strict';
const path=require('path'),crypto=require('crypto');const{DatabaseSync}=require('node:sqlite');const DB=process.env.PURPCLAW_SESSION_DB||path.join(path.resolve(__dirname,'..'),'.purpclaw','state.db'),db=(require('fs').mkdirSync(path.dirname(DB),{recursive:true}),new DatabaseSync(DB));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;CREATE TABLE IF NOT EXISTS knowledge_indexes(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,type TEXT NOT NULL,config TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS index_nodes(id TEXT PRIMARY KEY,index_id TEXT NOT NULL,document_id TEXT NOT NULL,parent_id TEXT,kind TEXT NOT NULL,text TEXT NOT NULL,summary TEXT,metadata TEXT NOT NULL,vector TEXT,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_index_nodes ON index_nodes(index_id,document_id);`);
const uid=prefix=>`${prefix}-${crypto.randomUUID()}`,now=()=>new Date().toISOString(),tokens=text=>String(text||'').toLowerCase().match(/[\p{L}\p{N}_-]+/gu)||[];
function vector(text,size=96){const out=Array(size).fill(0);for(const token of tokens(text)){const hash=crypto.createHash('sha256').update(token).digest(),slot=hash.readUInt32BE(0)%size;out[slot]+=1;}const norm=Math.sqrt(out.reduce((sum,value)=>sum+value*value,0))||1;return out.map(value=>value/norm);}
function cosine(a,b){let value=0;for(let i=0;i<Math.min(a.length,b.length);i++)value+=a[i]*b[i];return value;}
function create(name,type='vector',config={}){if(!['vector','keyword','summary','tree'].includes(type))throw new Error(`unsupported index type: ${type}`);const id=uid('index'),stamp=now();db.prepare('INSERT INTO knowledge_indexes VALUES(?,?,?,?,?,?)').run(id,name,type,JSON.stringify(config),stamp,stamp);return get(id);}
function get(idOrName){const row=db.prepare('SELECT * FROM knowledge_indexes WHERE id=? OR name=?').get(idOrName,idOrName);return row?{...row,config:JSON.parse(row.config)}:null;}
function list(){return db.prepare('SELECT * FROM knowledge_indexes ORDER BY name').all().map(row=>({...row,config:JSON.parse(row.config)}));}
function split(text,size=800,overlap=80){const out=[];for(let at=0;at<text.length;at+=Math.max(1,size-overlap))out.push(text.slice(at,at+size));return out.filter(Boolean);}
function add(indexId,documents=[]){const index=get(indexId);if(!index)throw new Error(`index not found: ${indexId}`);const insert=db.prepare('INSERT INTO index_nodes VALUES(?,?,?,?,?,?,?,?,?,?)');let count=0;for(const input of documents){const document=typeof input==='string'?{text:input}:input,documentId=document.id||uid('doc'),text=String(document.text||document.content||''),summary=document.summary||text.slice(0,index.config.summary_chars||500),metadata=document.metadata||{};if(!text)continue;if(index.type==='summary'){insert.run(uid('node'),index.id,documentId,null,'summary',text,summary,JSON.stringify(metadata),JSON.stringify(vector(summary)),now());count++;continue;}if(index.type==='tree'){const root=uid('node');insert.run(root,index.id,documentId,null,'root',text,summary,JSON.stringify(metadata),JSON.stringify(vector(summary)),now());count++;for(const chunk of split(text,index.config.chunk_size||800,index.config.overlap||80)){insert.run(uid('node'),index.id,documentId,root,'leaf',chunk,chunk.slice(0,200),JSON.stringify(metadata),JSON.stringify(vector(chunk)),now());count++;}continue;}for(const chunk of split(text,index.config.chunk_size||800,index.config.overlap||80)){insert.run(uid('node'),index.id,documentId,null,'chunk',chunk,summary,JSON.stringify(metadata),index.type==='vector'?JSON.stringify(vector(chunk)):null,now());count++;}}db.prepare('UPDATE knowledge_indexes SET updated_at=? WHERE id=?').run(now(),index.id);return{index_id:index.id,nodes:count};}
function keywordScore(text,query){const terms=tokens(query),hay=tokens(text),counts=new Map();for(const token of hay)counts.set(token,(counts.get(token)||0)+1);return terms.reduce((sum,term)=>sum+(counts.get(term)||0),0)/Math.max(hay.length,1);}
function query(indexId,text,options={}){const index=get(indexId);if(!index)throw new Error(`index not found: ${indexId}`);const rows=db.prepare('SELECT * FROM index_nodes WHERE index_id=?').all(index.id),qvec=vector(text),scored=rows.map(row=>{let score;if(index.type==='keyword')score=keywordScore(row.text,text);else if(index.type==='summary')score=cosine(JSON.parse(row.vector||'[]'),qvec);else if(index.type==='tree')score=cosine(JSON.parse(row.vector||'[]'),qvec)+(row.kind==='leaf'?.05:0);else score=cosine(JSON.parse(row.vector||'[]'),qvec);return{id:row.id,index_id:index.id,index_type:index.type,document_id:row.document_id,parent_id:row.parent_id,kind:row.kind,text:row.kind==='root'?row.summary:row.text,summary:row.summary,metadata:JSON.parse(row.metadata),score};}).filter(item=>item.score>Number(options.min_score||0)).sort((a,b)=>b.score-a.score);return scored.slice(0,Math.max(1,Math.min(Number(options.top_k)||5,100)));}
function remove(id){db.prepare('DELETE FROM index_nodes WHERE index_id=?').run(id);return db.prepare('DELETE FROM knowledge_indexes WHERE id=?').run(id).changes>0;}
module.exports={create,get,list,add,query,remove,vector,cosine,keywordScore,DB};
