'use strict';const path=require('path'),crypto=require('crypto');const{DatabaseSync}=require('node:sqlite');const DB=process.env.PURPCLAW_SESSION_DB||path.join(process.cwd(),'.purpclaw','state.db'),db=new DatabaseSync(DB),controllers=new Map();
db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;CREATE TABLE IF NOT EXISTS invocations(id TEXT PRIMARY KEY,kind TEXT NOT NULL,target TEXT,status TEXT NOT NULL,input TEXT,output TEXT,error TEXT,session_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS invocation_events(id INTEGER PRIMARY KEY AUTOINCREMENT,invocation_id TEXT NOT NULL,type TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_invocation_events ON invocation_events(invocation_id,id);`);const uid=()=>`invocation-${crypto.randomUUID()}`,now=()=>new Date().toISOString();
function event(id,type,payload={}){db.prepare('INSERT INTO invocation_events(invocation_id,type,payload,created_at) VALUES(?,?,?,?)').run(id,type,JSON.stringify(payload),now());}
function update(id,patch){const current=get(id);if(!current)throw new Error(`invocation not found: ${id}`);const next={...current,...patch,updated_at:now()};db.prepare('UPDATE invocations SET status=?,output=?,error=?,session_id=?,updated_at=? WHERE id=?').run(next.status,JSON.stringify(next.output??null),next.error||null,next.session_id||null,next.updated_at,id);return get(id);}
function get(id){const row=db.prepare('SELECT * FROM invocations WHERE id=?').get(id);return row?{...row,input:JSON.parse(row.input||'null'),output:JSON.parse(row.output||'null')}:null;}
function list(limit=50){return db.prepare('SELECT * FROM invocations ORDER BY created_at DESC LIMIT ?').all(Math.max(1,Math.min(+limit||50,500))).map(row=>({...row,input:JSON.parse(row.input||'null'),output:JSON.parse(row.output||'null')}));}
function events(id,after=0,limit=1000){return db.prepare('SELECT * FROM invocation_events WHERE invocation_id=? AND id>? ORDER BY id LIMIT ?').all(id,Number(after)||0,Math.max(1,Math.min(+limit||1000,5000))).map(row=>({...row,payload:JSON.parse(row.payload)}));}
async function execute(gateway,invocation,options={}){const controller=new AbortController();controllers.set(invocation.id,controller);update(invocation.id,{status:'running'});event(invocation.id,'invocation.started',{kind:invocation.kind,target:invocation.target});const forward=(type,payload)=>{if(!payload.session_id||!invocation.session_id||payload.session_id===invocation.session_id)event(invocation.id,type,payload);},handlers={};for(const type of gateway.capabilities().events){handlers[type]=payload=>forward(type,payload);gateway.on(type,handlers[type]);}try{let result;if(invocation.kind==='agent')result=await gateway.dispatch('agent.run',{agent:invocation.target,input:invocation.input,signal:controller.signal});else if(invocation.kind==='workflow')result=await gateway.dispatch('workflow.run',{workflow:invocation.target,input:invocation.input});else if(invocation.kind==='team')result=await gateway.dispatch('team.run',{team_id:invocation.target,task:typeof invocation.input==='string'?invocation.input:invocation.input?.task});else result=await gateway.submit({prompt:typeof invocation.input==='string'?invocation.input:JSON.stringify(invocation.input),platform:'invocation',operator_initiated:false});invocation.session_id=result.session_id||result.state?.session_id||null;const done=update(invocation.id,{status:'completed',output:result,session_id:invocation.session_id});event(invocation.id,'invocation.completed',{output:result});return done;}catch(error){const status=controller.signal.aborted?'canceled':'failed',failed=update(invocation.id,{status,error:error.message});event(invocation.id,`invocation.${status}`,{error:error.message});return failed;}finally{controllers.delete(invocation.id);for(const[type,handler]of Object.entries(handlers))gateway.off(type,handler);}}
function start(gateway,params={}){const id=uid(),stamp=now(),invocation={id,kind:params.kind||'prompt',target:params.target||null,status:'queued',input:params.input??params.prompt,output:null,error:null,session_id:null,created_at:stamp,updated_at:stamp};db.prepare('INSERT INTO invocations VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,invocation.kind,invocation.target,'queued',JSON.stringify(invocation.input??null),null,null,null,stamp,stamp);const promise=execute(gateway,invocation,params);if(params.blocking)return promise;promise.catch(()=>{});return get(id);}
function cancel(id,gateway){const invocation=get(id);if(!invocation)throw new Error(`invocation not found: ${id}`);controllers.get(id)?.abort();if(invocation.session_id)try{gateway.interrupt(invocation.session_id);}catch{}event(id,'invocation.cancel.requested',{});return update(id,{status:'canceling'});}
async function resume(gateway,id,params={}){const invocation=get(id);if(!invocation)throw new Error(`invocation not found: ${id}`);if(!['failed','canceled','canceling'].includes(invocation.status))throw new Error(`invocation cannot resume from ${invocation.status}`);event(id,'invocation.resumed',{});return execute(gateway,{...invocation,input:params.input??invocation.input},params);}
module.exports={start,get,list,events,cancel,resume,execute,DB};
