// RECIPE capability (role=recipe in registry/workflow-authority.json), NOT a
// workflow authority. Linear YAML macros: sequential prompt/tool/recipe steps,
// no run persistence. For branching, parallelism, approvals or resumable runs,
// use the canonical workflow authority lib/workflow-manager.js.
'use strict';const fs=require('fs'),path=require('path'),yaml=require('js-yaml');const{ToolRuntime}=require('./tool-runtime');
function dirs(cwd=process.cwd()){return[path.join(cwd,'.purpclaw','recipes'),path.join(cwd,'recipes'),path.join(__dirname,'..','recipes')];}
function files(cwd){const result=[];for(const dir of dirs(cwd)){try{for(const entry of fs.readdirSync(dir)){if(/\.ya?ml$/i.test(entry))result.push(path.join(dir,entry));}}catch{}}return[...new Set(result)];}
function load(ref,cwd=process.cwd()){const direct=path.resolve(cwd,String(ref||''));const candidates=[direct,...files(cwd).filter(file=>path.basename(file).replace(/\.ya?ml$/i,'')===ref)];const file=candidates.find(candidate=>fs.existsSync(candidate));if(!file)throw new Error(`recipe not found: ${ref}`);const value=yaml.load(fs.readFileSync(file,'utf8'));if(!value||!Array.isArray(value.steps))throw new Error(`invalid recipe: ${file}`);return{...value,name:value.name||path.basename(file).replace(/\.ya?ml$/i,''),path:file};}
function list(cwd=process.cwd()){return files(cwd).map(file=>{try{const value=load(file,cwd);return{name:value.name,description:value.description||'',parameters:value.parameters||{},steps:value.steps.length,path:file}}catch(error){return{name:path.basename(file),error:error.message,path:file}}});}
function interpolate(value,context){if(typeof value==='string')return value.replace(/\{\{\s*([^}]+)\s*\}\}/g,(_,key)=>{const parts=key.trim().split('.');let current=context;for(const part of parts)current=current?.[part];return current==null?'':typeof current==='string'?current:JSON.stringify(current)});if(Array.isArray(value))return value.map(item=>interpolate(item,context));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,item])=>[key,interpolate(item,context)]));return value;}
function parameters(recipe,input={}){const result={};for(const[name,spec]of Object.entries(recipe.parameters||{})){const value=input[name]??spec?.default;if((value===undefined||value==='')&&spec?.required)throw new Error(`recipe parameter required: ${name}`);result[name]=value}return{...result,...input};}
async function run(gateway,ref,options={}){const cwd=options.cwd||gateway.cwd||process.cwd(),recipe=typeof ref==='object'?ref:load(ref,cwd),context={params:parameters(recipe,options.parameters||{}),steps:{}};let sessionId=options.session_id||gateway.activeSessionId;gateway.emit('recipe.started',{recipe:recipe.name,session_id:sessionId});const runtime=new ToolRuntime({approvalCallback:request=>gateway.waitForApproval(request,options.signal)});
for(let index=0;index<recipe.steps.length;index++){const raw=recipe.steps[index],step=interpolate(raw,context),id=step.id||`step_${index+1}`;gateway.emit('recipe.step.started',{recipe:recipe.name,step:id,index,session_id:sessionId});let output;if(step.prompt){const result=await gateway.submit({prompt:step.prompt,session_id:sessionId,platform:'recipe',operator_initiated:options.operator_initiated===true,max_turns:step.max_turns||options.max_turns});sessionId=result.session_id;output=result;}else if(step.tool){output=await runtime.invoke(step.tool,step.arguments||{},{sessionId,operatorInitiated:options.operator_initiated===true,approvalCallback:request=>gateway.waitForApproval(request,options.signal)});if(output.ok===false)throw new Error(`recipe step ${id} failed: ${output.error}`);}else if(step.recipe){output=await run(gateway,step.recipe,{...options,session_id:sessionId,parameters:step.parameters||{}});sessionId=output.session_id||sessionId;}else throw new Error(`recipe step ${id} has no prompt, tool, or recipe`);context.steps[id]={output};gateway.emit('recipe.step.completed',{recipe:recipe.name,step:id,index,session_id:sessionId,output});}
const result={recipe:recipe.name,session_id:sessionId,steps:context.steps};gateway.emit('recipe.completed',result);return result;}
module.exports={load,list,run,interpolate,parameters,dirs};
