'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const IGNORE=new Set(['node_modules','.git','.next','dist','build','coverage','release','.purpclaw','.venv','venv','vendor','.archive','archive']);
const CODE_EXT=new Set(['.js','.cjs','.mjs','.ts','.tsx','.jsx','.py','.rs','.go','.java','.cs','.cpp','.c','.h','.rb','.php','.swift','.kt']),CACHE=new Map();
function files(root,limit=5000){const out=[];function walk(dir){if(out.length>=limit)return;for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(IGNORE.has(entry.name)||/^purpclaw-master\b/i.test(entry.name))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())walk(full);else if(CODE_EXT.has(path.extname(entry.name).toLowerCase()))out.push(full);if(out.length>=limit)return}}walk(root);return out;}
function symbols(content,ext){const results=[],patterns=ext==='.py'?[/^\s*(?:async\s+)?def\s+([A-Za-z_]\w*)\s*\(([^)]*)/gm,/^\s*class\s+([A-Za-z_]\w*)/gm]:[/\b(?:export\s+)?(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(([^)]*)/g,/\bclass\s+([A-Za-z_$][\w$]*)/g,/\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?\(/g];for(const pattern of patterns){let match;while((match=pattern.exec(content))&&results.length<40)results.push(`${match[1]}${match[2]!==undefined?`(${match[2].replace(/\s+/g,' ').slice(0,100)})`:''}`)}return[...new Set(results)];}
function build(root=process.cwd(),opts={}){
  root=path.resolve(root);const maxChars=Math.max(1000,Number(opts.maxChars)||12000),queryTerms=String(opts.query||'').toLowerCase().split(/[^a-z0-9_$-]+/).filter(term=>term.length>2),cacheKey=`${root}:${maxChars}:${opts.maxFiles||5000}:${queryTerms.join(',')}`,cached=CACHE.get(cacheKey);if(cached&&Date.now()-cached.at<(opts.cacheMs??30000))return cached.value;
  const entries=[];for(const file of files(root,opts.maxFiles||5000)){try{const stat=fs.statSync(file);if(stat.size>1024*1024)continue;const content=fs.readFileSync(file,'utf8'),found=symbols(content,path.extname(file).toLowerCase());if(!found.length)continue;const rel=path.relative(root,file).replace(/\\/g,'/'),references=(content.match(/(?:import|require\s*\()/g)||[]).length,searchable=`${rel} ${found.join(' ')}`.toLowerCase(),relevance=queryTerms.reduce((sum,term)=>sum+(searchable.includes(term)?100:0),0),score=Math.min(found.length,12)*3+references+relevance+Math.max(0,10-rel.split('/').length);entries.push({path:rel,symbols:found,score,mtime:stat.mtimeMs});}catch{}}
  entries.sort((a,b)=>b.score-a.score||a.path.localeCompare(b.path));let text='## Repository map\n';const selected=[];for(const entry of entries){const shown=entry.symbols.slice(0,12),block=`${entry.path}:\n  ${shown.join(', ')}${entry.symbols.length>shown.length?`, +${entry.symbols.length-shown.length} more`:''}\n`;if(text.length+block.length>maxChars)continue;text+=block;selected.push(entry)}
  const value={root,text:text.trim(),files:selected.length,totalFiles:entries.length,hash:crypto.createHash('sha256').update(text).digest('hex')};CACHE.set(cacheKey,{at:Date.now(),value});return value;
}
module.exports={build,files,symbols};
