'use strict';
const path=require('path'),crypto=require('crypto');const{DatabaseSync}=require('node:sqlite');
const DB=process.env.PURPCLAW_SESSION_DB||path.join(path.resolve(__dirname,'..'),'.purpclaw','state.db'),db=(require('fs').mkdirSync(path.dirname(DB),{recursive:true}),new DatabaseSync(DB));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;CREATE TABLE IF NOT EXISTS agent_teams(id TEXT PRIMARY KEY,name TEXT NOT NULL,config TEXT NOT NULL,state TEXT NOT NULL,status TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);`);
const uid=()=>`team-${crypto.randomUUID()}`,now=()=>new Date().toISOString(),clone=value=>JSON.parse(JSON.stringify(value??null));
function validate(config){if(!config?.name)throw new Error('team name is required');if(!Array.isArray(config.participants)||!config.participants.length)throw new Error('team requires participants');const names=new Set();for(const agent of config.participants){if(!agent.name)throw new Error('participant name is required');if(names.has(agent.name))throw new Error(`duplicate participant: ${agent.name}`);names.add(agent.name);}if(!['round_robin','selector','swarm','hierarchical'].includes(config.mode||'round_robin'))throw new Error(`unsupported team mode: ${config.mode}`);return{version:'1.0',mode:'round_robin',termination:[{type:'max_messages',value:20}],...clone(config)};}
function persist(team){const stamp=now();db.prepare(`INSERT INTO agent_teams VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET config=excluded.config,state=excluded.state,status=excluded.status,updated_at=excluded.updated_at`).run(team.id,team.config.name,JSON.stringify(team.config),JSON.stringify(team.state),team.status,team.createdAt||stamp,stamp);return publicTeam(team);}
function hydrate(row){return row?{id:row.id,config:JSON.parse(row.config),state:JSON.parse(row.state),status:row.status,createdAt:row.created_at,updatedAt:row.updated_at}:null;}
function get(id){return hydrate(db.prepare('SELECT * FROM agent_teams WHERE id=?').get(id));}
function list(limit=50){return db.prepare('SELECT id,name,status,created_at,updated_at FROM agent_teams ORDER BY updated_at DESC LIMIT ?').all(Math.max(1,Math.min(+limit||50,500)));}
function publicTeam(team){return{id:team.id,name:team.config.name,mode:team.config.mode,status:team.status,config:team.config,state:team.state};}
function create(config){config=validate(config);const stamp=now(),team={id:config.id||uid(),config,state:{version:'1.0',turn:0,history:[],participantStates:{},startedAt:null,endedAt:null,stopReason:null,externalStop:false},status:'idle',createdAt:stamp,updatedAt:stamp};persist(team);return publicTeam(team);}
function exportState(id){const team=get(id);if(!team)throw new Error(`team not found: ${id}`);return{schema:'purpclaw.team-state.v1',config:team.config,state:team.state,status:team.status};}
function importState(value){if(value?.schema!=='purpclaw.team-state.v1')throw new Error('unsupported team state schema');const created=create({...value.config,id:undefined,name:`${value.config.name} (imported)`}),team=get(created.id);team.state=clone(value.state);team.status=value.status==='running'?'paused':value.status;persist(team);return publicTeam(team);}
function termination(team,last,elapsed){for(const condition of team.config.termination||[]){let met=false,reason='';switch(condition.type){case'max_messages':met=team.state.history.length>=Number(condition.value);reason=`max messages ${condition.value}`;break;case'text':met=new RegExp(condition.value,condition.flags||'i').test(last?.content||'');reason=`text matched ${condition.value}`;break;case'token_usage':met=(team.state.usage?.total_tokens||0)>=Number(condition.value);reason=`token limit ${condition.value}`;break;case'timeout':met=elapsed>=Number(condition.seconds||condition.value)*1000;reason=`timeout ${condition.seconds||condition.value}s`;break;case'handoff':met=last?.handoff===condition.target;reason=`handoff to ${condition.target}`;break;case'external':met=team.state.externalStop===true;reason='external stop';break;default:throw new Error(`unknown termination condition: ${condition.type}`);}if(met)return{met:true,reason,type:condition.type};}return{met:false};}
async function choose(team,adapter){const participants=team.config.participants,state=team.state,mode=team.config.mode;if(mode==='round_robin')return participants[state.turn%participants.length];if(mode==='swarm'){const handoff=[...state.history].reverse().find(item=>item.handoff)?.handoff;return participants.find(agent=>agent.name===handoff)||participants[state.turn%participants.length];}if(mode==='selector'||mode==='hierarchical'){const name=await adapter.select?.(team.config,state);const selected=participants.find(agent=>agent.name===name);if(selected)return selected;return participants[state.turn%participants.length];}return participants[0];}
async function run(id,task,adapter,options={}){const team=get(id);if(!team)throw new Error(`team not found: ${id}`);if(team.status==='running')throw new Error('team is already running');if(['completed','failed','stopped'].includes(team.status)&&!options.restart)throw new Error(`team is terminal: ${team.status}`);if(options.restart)team.state={version:'1.0',turn:0,history:[],participantStates:{},startedAt:null,endedAt:null,stopReason:null,externalStop:false};team.status='running';team.state.startedAt=team.state.startedAt||now();if(task)team.state.history.push({type:'message',role:'user',source:'user',content:String(task),timestamp:now()});persist(team);const emit=(type,payload={})=>options.onEvent?.({type,team_id:team.id,...payload}),started=Date.now(),hardMax=Math.max(1,Math.min(Number(options.maxTurns)||100,1000));emit('team.started',{task,mode:team.config.mode});try{while(team.state.turn<hardMax){const before=termination(team,team.state.history.at(-1),Date.now()-started);if(before.met){team.status='completed';team.state.stopReason=before.reason;break;}const participant=await choose(team,adapter);emit('team.speaker.selected',{participant:participant.name,turn:team.state.turn});const response=await adapter.respond(participant,{task,history:clone(team.state.history),state:clone(team.state.participantStates[participant.name]||{}),team:team.config});const entry={type:'message',role:'agent',source:participant.name,content:String(response?.content??response??''),handoff:response?.handoff||null,usage:response?.usage||null,timestamp:now()};team.state.history.push(entry);team.state.participantStates[participant.name]={...(team.state.participantStates[participant.name]||{}),...(response?.state||{})};if(response?.usage){const usage=team.state.usage||(team.state.usage={prompt_tokens:0,completion_tokens:0,total_tokens:0});for(const key of Object.keys(usage))usage[key]+=Number(response.usage[key]||0);}team.state.turn++;persist(team);emit('team.message',entry);const after=termination(team,entry,Date.now()-started);if(after.met){team.status='completed';team.state.stopReason=after.reason;break;}if(team.state.externalStop){team.status='stopped';team.state.stopReason='external stop';break;}}if(team.status==='running'){team.status='stopped';team.state.stopReason=`hard turn limit ${hardMax}`;}team.state.endedAt=now();persist(team);emit('team.completed',{status:team.status,reason:team.state.stopReason});return publicTeam(team);}catch(error){team.status='failed';team.state.stopReason=error.message;team.state.endedAt=now();persist(team);emit('team.failed',{error:error.message});throw error;}}
function stop(id){const team=get(id);if(!team)throw new Error(`team not found: ${id}`);team.state.externalStop=true;if(team.status!=='running')team.status='stopped';persist(team);return publicTeam(team);}
async function replay(id,fromTurn,adapter,options={}){const team=get(id);if(!team)throw new Error(`team not found: ${id}`);const user=team.state.history.find(item=>item.role==='user'),keep=Math.max(1,Number(fromTurn)||1);team.state.history=team.state.history.slice(0,keep);team.state.turn=team.state.history.filter(item=>item.role==='agent').length;team.state.endedAt=null;team.state.stopReason=null;team.state.externalStop=false;team.status='paused';persist(team);return run(id,user?.content,adapter,{...options,restart:false});}
async function train(id,examples,adapter,options={}){if(!get(id))throw new Error(`team not found: ${id}`);const records=[];for(const example of examples||[]){const result=await run(id,example.task,adapter,{restart:true,maxTurns:options.maxTurns});const transcript=result.state.history.filter(item=>item.role==='agent').map(item=>item.content).join('\n'),score=typeof options.score==='function'?await options.score(example,transcript,result):(example.expected?Number(transcript.includes(example.expected)):1);records.push({task:example.task,expected:example.expected||null,score,transcript,timestamp:now()});}const team=get(id);team.state.training=[...(team.state.training||[]),...records];team.config.training_examples=[...(team.config.training_examples||[]),...records.filter(item=>item.score>0).map(item=>({task:item.task,response:item.transcript}))];persist(team);return{team_id:id,examples:records.length,score:records.reduce((sum,item)=>sum+item.score,0)/Math.max(records.length,1),records};}
module.exports={create,get,list,run,stop,replay,train,exportState,importState,termination,validate,DB};
