'use strict';const path=require('path'),crypto=require('crypto');const{DatabaseSync}=require('node:sqlite');const DB=process.env.PURPCLAW_SESSION_DB||path.join(process.cwd(),'.purpclaw','state.db'),db=new DatabaseSync(DB);
db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;CREATE TABLE IF NOT EXISTS otel_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,time TEXT NOT NULL,severity TEXT NOT NULL,body TEXT NOT NULL,attributes TEXT NOT NULL,trace_id TEXT,span_id TEXT);CREATE TABLE IF NOT EXISTS otel_metrics(name TEXT NOT NULL,type TEXT NOT NULL,value REAL NOT NULL,attributes TEXT NOT NULL,time TEXT NOT NULL);CREATE INDEX IF NOT EXISTS idx_otel_metrics ON otel_metrics(name,time);`);const now=()=>new Date().toISOString(),nanos=value=>String(BigInt(new Date(value).getTime())*1000000n),hex=(value,length)=>crypto.createHash('sha256').update(String(value||'')).digest('hex').slice(0,length),attrs=value=>Object.entries(value||{}).map(([key,item])=>({key,value:typeof item==='number'?{doubleValue:item}:typeof item==='boolean'?{boolValue:item}:{stringValue:typeof item==='string'?item:JSON.stringify(item)}}));
function log(severity,body,attributes={},context={}){const time=now();db.prepare('INSERT INTO otel_logs(time,severity,body,attributes,trace_id,span_id) VALUES(?,?,?,?,?,?)').run(time,String(severity).toUpperCase(),String(body),JSON.stringify(attributes),context.traceId||null,context.spanId||null);return{time,severity,body,attributes,...context};}
function metric(name,value,type='counter',attributes={}){if(!['counter','gauge','histogram'].includes(type))throw new Error(`invalid metric type: ${type}`);db.prepare('INSERT INTO otel_metrics VALUES(?,?,?,?,?)').run(name,type,Number(value),JSON.stringify(attributes),now());}
function increment(name,value=1,attributes={}){metric(name,value,'counter',attributes);}function gauge(name,value,attributes={}){metric(name,value,'gauge',attributes);}function histogram(name,value,attributes={}){metric(name,value,'histogram',attributes);}
function resource(serviceName='purpclaw'){return{attributes:attrs({'service.name':serviceName,'service.version':'0.9.0-rc'})};}
function toOTLPLogs(options={}){const rows=db.prepare('SELECT * FROM otel_logs ORDER BY id').all();return{resourceLogs:[{resource:resource(options.serviceName),scopeLogs:[{scope:{name:'purpclaw.telemetry'},logRecords:rows.map(row=>({timeUnixNano:nanos(row.time),severityText:row.severity,body:{stringValue:row.body},attributes:attrs(JSON.parse(row.attributes)),...(row.trace_id?{traceId:hex(row.trace_id,32)}:{}),...(row.span_id?{spanId:hex(row.span_id,16)}:{})}))}]}]};}
function toOTLPMetrics(options={}){const rows=db.prepare('SELECT * FROM otel_metrics ORDER BY time').all(),groups=new Map();for(const row of rows){const key=`${row.name}\0${row.type}`,group=groups.get(key)||{name:row.name,type:row.type,points:[]};group.points.push({asDouble:row.value,timeUnixNano:nanos(row.time),attributes:attrs(JSON.parse(row.attributes))});groups.set(key,group);}return{resourceMetrics:[{resource:resource(options.serviceName),scopeMetrics:[{scope:{name:'purpclaw.telemetry'},metrics:[...groups.values()].map(group=>group.type==='counter'?{name:group.name,sum:{aggregationTemporality:2,isMonotonic:true,dataPoints:group.points}}:group.type==='histogram'?{name:group.name,gauge:{dataPoints:group.points}}:{name:group.name,gauge:{dataPoints:group.points}})}]}]};}
async function post(endpoint,pathName,body,headers={}){const url=`${endpoint.replace(/\/$/,'')}${pathName}`,response=await fetch(url,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});if(!response.ok)throw new Error(`OTLP export failed ${pathName}: ${response.status}`);return{status:response.status,url};}
async function exportOTLP(options={}){const endpoint=options.endpoint||process.env.OTEL_EXPORTER_OTLP_ENDPOINT;if(!endpoint)throw new Error('OTLP endpoint is required');const[logs,metrics]=await Promise.all([post(endpoint,'/v1/logs',toOTLPLogs(options),options.headers),post(endpoint,'/v1/metrics',toOTLPMetrics(options),options.headers)]);return{ok:true,logs,metrics};}
module.exports={log,metric,increment,gauge,histogram,toOTLPLogs,toOTLPMetrics,exportOTLP,DB};
