'use strict';
const path=require('path'),crypto=require('crypto');const{DatabaseSync}=require('node:sqlite');
const DB=process.env.PURPCLAW_SESSION_DB||path.join(process.cwd(),'.purpclaw','state.db'),db=new DatabaseSync(DB),processors=new Set();
db.exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;CREATE TABLE IF NOT EXISTS traces(trace_id TEXT PRIMARY KEY,name TEXT NOT NULL,status TEXT NOT NULL,metadata TEXT,started_at TEXT NOT NULL,ended_at TEXT);CREATE TABLE IF NOT EXISTS spans(span_id TEXT PRIMARY KEY,trace_id TEXT NOT NULL,parent_id TEXT,name TEXT NOT NULL,kind TEXT NOT NULL,status TEXT NOT NULL,input TEXT,output TEXT,error TEXT,metadata TEXT,started_at TEXT NOT NULL,ended_at TEXT);CREATE INDEX IF NOT EXISTS idx_spans_trace ON spans(trace_id,started_at);`);
const id=prefix=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,10)}`,safe=(value,sensitive)=>JSON.stringify(sensitive?'[REDACTED]':value??null),notify=(hook,value)=>{for(const processor of processors)try{processor[hook]?.(value);}catch{}};
function startTrace(name,metadata={}){const traceId=id('trace'),startedAt=new Date().toISOString(),value={traceId,name,status:'running',metadata,startedAt};db.prepare('INSERT INTO traces VALUES(?,?,?,?,?,NULL)').run(traceId,name,'running',JSON.stringify(metadata),startedAt);notify('onTraceStart',value);return traceId;}
function endTrace(traceId,status='complete',metadata){const endedAt=new Date().toISOString();db.prepare('UPDATE traces SET status=?,metadata=COALESCE(?,metadata),ended_at=? WHERE trace_id=?').run(status,metadata?JSON.stringify(metadata):null,endedAt,traceId);notify('onTraceEnd',get(traceId));}
function startSpan(traceId,name,options={}){const spanId=id('span'),startedAt=new Date().toISOString(),value={spanId,traceId,parentId:options.parentId||null,name,kind:options.kind||'internal',status:'running',input:options.sensitive?'[REDACTED]':options.input??null,metadata:options.metadata||{},startedAt};db.prepare('INSERT INTO spans VALUES(?,?,?,?,?,?,?,?,?,?,?,NULL)').run(spanId,traceId,value.parentId,name,value.kind,'running',safe(options.input,options.sensitive),null,null,JSON.stringify(value.metadata),startedAt);notify('onSpanStart',value);return spanId;}
function endSpan(spanId,options={}){const endedAt=new Date().toISOString(),status=options.status||(options.error?'error':'complete');db.prepare('UPDATE spans SET status=?,output=?,error=?,ended_at=? WHERE span_id=?').run(status,safe(options.output,options.sensitive),options.error?String(options.error):null,endedAt,spanId);const row=db.prepare('SELECT trace_id FROM spans WHERE span_id=?').get(spanId);if(row)notify('onSpanEnd',get(row.trace_id)?.spans.find(span=>span.span_id===spanId));}
function get(traceId){const trace=db.prepare('SELECT * FROM traces WHERE trace_id=?').get(traceId);if(!trace)return null;const spans=db.prepare('SELECT * FROM spans WHERE trace_id=? ORDER BY started_at').all(traceId);return{...trace,metadata:JSON.parse(trace.metadata||'{}'),spans:spans.map(span=>({...span,input:JSON.parse(span.input||'null'),output:JSON.parse(span.output||'null'),metadata:JSON.parse(span.metadata||'{}')}))};}
function list(limit=50){return db.prepare('SELECT * FROM traces ORDER BY started_at DESC LIMIT ?').all(Math.max(1,Math.min(Number(limit)||50,500))).map(trace=>({...trace,metadata:JSON.parse(trace.metadata||'{}')}));}
function addProcessor(processor){processors.add(processor);return()=>processors.delete(processor);}
const hex=(value,length)=>crypto.createHash('sha256').update(String(value)).digest('hex').slice(0,length),nanos=value=>String(BigInt(new Date(value).getTime())*1000000n),attrs=value=>Object.entries(value||{}).map(([key,item])=>({key,value:typeof item==='number'?{doubleValue:item}:typeof item==='boolean'?{boolValue:item}:{stringValue:typeof item==='string'?item:JSON.stringify(item)}}));
function toOTLP(traceId,options={}){const trace=get(traceId);if(!trace)throw new Error(`trace not found: ${traceId}`);return{resourceSpans:[{resource:{attributes:attrs({'service.name':options.serviceName||'purpclaw','service.version':options.serviceVersion||'0.9.0-rc'})},scopeSpans:[{scope:{name:'purpclaw.agent-gateway',version:'1'},spans:trace.spans.map(span=>({traceId:hex(trace.trace_id,32),spanId:hex(span.span_id,16),...(span.parent_id?{parentSpanId:hex(span.parent_id,16)}:{}),name:span.name,kind:span.kind==='server'?2:span.kind==='client'?3:1,startTimeUnixNano:nanos(span.started_at),endTimeUnixNano:nanos(span.ended_at||span.started_at),attributes:attrs({...span.metadata,'purpclaw.input':span.input,'purpclaw.output':span.output}),status:{code:span.status==='error'?2:1,message:span.error||''}}))}]}]};}
async function exportOTLP(traceId,options={}){const endpoint=options.endpoint||process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT||process.env.OTEL_EXPORTER_OTLP_ENDPOINT;if(!endpoint)throw new Error('OTLP endpoint is required');const url=endpoint.endsWith('/v1/traces')?endpoint:`${endpoint.replace(/\/$/,'')}/v1/traces`,body=toOTLP(traceId,options),response=await fetch(url,{method:'POST',headers:{'content-type':'application/json',...(options.headers||{})},body:JSON.stringify(body)});if(!response.ok)throw new Error(`OTLP export failed: ${response.status} ${await response.text()}`);return{ok:true,status:response.status,endpoint:url,spans:body.resourceSpans[0].scopeSpans[0].spans.length};}
module.exports={startTrace,endTrace,startSpan,endSpan,get,list,addProcessor,toOTLP,exportOTLP,DB};
