#!/usr/bin/env python
"""
PURPCLAW LoRA fine-tuning pipeline
═══════════════════════════════════════════════════════════════════════
Train a local model on the PURPCLAW training corpus (E:/training/raw/)
and export it to Ollama for the runtime to use.

Stack:
  - transformers (HF)
  - peft (LoRA)
  - trl (SFTTrainer)
  - bitsandbytes (4-bit QLoRA — fits 6GB VRAM)
  - llama.cpp (GGUF conversion)

Pipeline:
  1. Load NDJSON training data from E:/training/raw/YYYY-MM-DD.ndjson
  2. Convert to chatml / sharegpt format
  3. Load base model with 4-bit quantization
  4. Fine-tune with LoRA (r=16, alpha=32, target=all-linear)
  5. Merge LoRA into base
  6. Convert to GGUF (q4_k_m)
  7. Import to Ollama as `purpclaw-quill`
  8. Update LLM_MODEL in .env to point to it

Usage:
  python scripts/lora-train.py                       # full pipeline, default settings
  python scripts/lora-train.py --base qwen2.5-1.5b   # use a smaller base
  python scripts/lora-train.py --epochs 1             # quick test
  python scripts/lora-train.py --skip-export          # train only, no GGUF/Ollama

Note: requires ~6GB VRAM (RTX 2060 / GTX 1660). 4-bit quantization is
mandatory for our 6GB cards. For larger bases, run on a beefier box.

Install deps first:
  pip install peft trl bitsandbytes accelerate datasets
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

TRAIN_DIR  = Path(os.environ.get("PURPCLAW_TRAINING_DIR", "E:/training"))
RAW_DIR    = TRAIN_DIR / "raw"
ADAPTERS   = TRAIN_DIR / "adapters"
MERGED     = TRAIN_DIR / "merged"
GGUF_OUT   = TRAIN_DIR / "gguf"
OLLAMA_DIR = Path(os.environ.get("OLLAMA_MODELS", "C:/Users/Admin/.ollama/models"))

# Default base model — small enough to fit on 6GB VRAM with 4-bit quant
DEFAULT_BASE = "Qwen/Qwen2.5-1.5B-Instruct"
PURPCLAW_OLLAMA_NAME = "purpclaw-quill"

# 4-bit quantization config (QLoRA)
BNB_CONFIG = {
    "load_in_4bit": True,
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_compute_dtype": "float16",
    "bnb_4bit_use_double_quant": True,
}

# LoRA config (matches the AutoResearch ratchet's preferred settings)
LORA_CONFIG = {
    "r": 16,
    "lora_alpha": 32,
    "lora_dropout": 0.05,
    "bias": "none",
    "task_type": "CAUSAL_LM",
    "target_modules": ["q_proj", "k_proj", "v_proj", "o_proj",
                       "gate_proj", "up_proj", "down_proj"],
}

# Training config (single H100-ish settings, scaled for RTX 2060)
DEFAULT_TRAIN_CONFIG = {
    "num_train_epochs": 1,
    "per_device_train_batch_size": 4,
    "gradient_accumulation_steps": 4,    # effective batch 16
    "learning_rate": 2e-4,
    "lr_scheduler_type": "cosine",
    "warmup_ratio": 0.03,
    "max_seq_length": 2048,
    "fp16": True,
    "logging_steps": 5,
    "save_strategy": "epoch",
    "save_total_limit": 2,
    "report_to": "none",
}


def log(*args, **kwargs):
    print(f"[lora-train {datetime.now().strftime('%H:%M:%S')}]", *args, **kwargs, flush=True)


def load_personal_dataset(dataset_path):
    """Load a personal training dataset (ChatML JSON).
    Generated by lib/training/personal-dataset.js from user feedback.
    Each record is {messages: [{role, content}, ...], metadata: {...}}.
    """
    path = Path(dataset_path)
    if not path.exists():
        log(f"ERROR: personal dataset {path} doesn't exist")
        sys.exit(1)
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    log(f"loaded {len(data)} personal training examples from {path}")
    for i, ex in enumerate(data[:3]):
        msgs = ex.get('messages', [])
        log(f"  [{i}] {len(msgs)} messages — {ex.get('metadata', {}).get('type', 'unknown')}")
    return data


def load_training_ndjson():
    """Load NDJSON training files from E:/training/raw/.
    Each record has input/output fields from the training buffer.
    Returns a list of {messages: [{role, content}, ...]} examples.
    """
    if not RAW_DIR.exists():
        log(f"ERROR: training dir {RAW_DIR} doesn't exist")
        sys.exit(1)
    files = sorted(RAW_DIR.glob("*.ndjson"))
    if not files:
        log(f"ERROR: no ndjson files in {RAW_DIR}")
        log("Run `purpclaw training status` to see buffer state.")
        sys.exit(1)
    log(f"loading from {len(files)} ndjson file(s)…")
    examples = []
    for f in files:
        with open(f, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line: continue
                try:
                    t = json.loads(line)
                except json.JSONDecodeError:
                    continue

                # Native messages format
                if "messages" in t and isinstance(t["messages"], list) and t["messages"]:
                    examples.append({"messages": t["messages"]})
                    continue

                # {prompt, response} format
                if "prompt" in t and "response" in t:
                    examples.append({"messages": [
                        {"role": "user", "content": str(t["prompt"])[:2000]},
                        {"role": "assistant", "content": str(t["response"])[:2000]},
                    ]})
                    continue

                # Trajectory format from training-buffer.js
                job = t.get("job") or {}
                goal = job.get("goal")
                trajectory = t.get("trajectory") or []
                if not goal: continue

                # Find the assistant reply in the trajectory events
                assistant_reply = ""
                for ev in trajectory:
                    typ = ev.get("type", "")
                    if typ in ("research_group_complete", "kernel_completed", "job_complete", "completed"):
                        detail = ev.get("detail") or {}
                        if isinstance(detail, dict):
                            # Try synthesis first
                            assistant_reply = (
                                detail.get("synthesis")
                                or detail.get("result")
                                or detail.get("summary")
                                or ""
                            )
                            # Fall back to first member's answer
                            if not assistant_reply:
                                members = detail.get("members") or []
                                for m in members:
                                    if isinstance(m, dict) and m.get("status") == "ok" and m.get("answer"):
                                        assistant_reply = m["answer"]
                                        break
                            if not assistant_reply and detail.get("text"):
                                assistant_reply = detail["text"]
                        # If still nothing, use the event message
                        if not assistant_reply:
                            assistant_reply = ev.get("message", "")
                    if assistant_reply:
                        break

                if not assistant_reply:
                    continue

                examples.append({"messages": [
                    {"role": "user", "content": str(goal)[:2000]},
                    {"role": "assistant", "content": str(assistant_reply)[:4000]},
                ]})
    log(f"loaded {len(examples)} training examples")
    return examples


def to_hf_dataset(examples):
    """Convert to a Hugging Face dataset with messages format."""
    from datasets import Dataset
    return Dataset.from_list(examples)


def maybe_filter_trajectories(examples, min_score=0.0, require_assistant=True):
    """Drop low-quality trajectories. Optional, off by default."""
    before = len(examples)
    out = []
    for ex in examples:
        msgs = ex.get("messages", [])
        if require_assistant and not any(m.get("role") == "assistant" for m in msgs):
            continue
        out.append(ex)
    if len(out) < before:
        log(f"filtered: {before} → {len(out)}")
    return out


def train(base_model, examples, args):
    import torch
    from transformers import (
        AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig,
        TrainingArguments,
    )
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
    from trl import SFTTrainer, SFTConfig

    log(f"loading base model: {base_model}")
    log(f"  this may take 30-60s for cold cache, 6GB VRAM required")
    bnb = BitsAndBytesConfig(**BNB_CONFIG)
    tokenizer = AutoTokenizer.from_pretrained(base_model, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    model = AutoModelForCausalLM.from_pretrained(
        base_model,
        quantization_config=bnb,
        device_map="auto",
        trust_remote_code=True,
    )
    model = prepare_model_for_kbit_training(model)
    lora = LoraConfig(**LORA_CONFIG)
    model = get_peft_model(model, lora)
    model.print_trainable_parameters()

    train_cfg = dict(DEFAULT_TRAIN_CONFIG)
    train_cfg["num_train_epochs"] = args.epochs
    train_cfg["output_dir"] = str(ADAPTERS / base_model.replace("/", "_"))
    if args.batch_size:
        train_cfg["per_device_train_batch_size"] = args.batch_size
    # TRL 0.18+ SFTConfig uses `max_length`, not `max_seq_length`. Pop the
    # legacy key from the spread so it doesn't blow up SFTConfig.__init__.
    max_seq_length = train_cfg.pop("max_seq_length", 2048)
    log(f"training config: {train_cfg}")

    ds = to_hf_dataset(examples)
    sft_args = SFTConfig(
      **train_cfg,
      dataset_text_field=None,   # we use 'messages' format
      packing=False,
      max_length=max_seq_length,
    )
    trainer = SFTTrainer(
        model=model,
        train_dataset=ds,
        args=sft_args,
        processing_class=tokenizer,
    )
    log("starting training…")
    trainer.train()
    log("training done")

    adapter_dir = Path(train_cfg["output_dir"])
    trainer.save_model(adapter_dir)
    log(f"adapter saved to {adapter_dir}")
    return adapter_dir, tokenizer


def merge(adapter_dir, base_model):
    """Merge LoRA adapter into the base model for export."""
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import PeftModel

    log(f"merging LoRA into {base_model}…")
    base = AutoModelForCausalLM.from_pretrained(
        base_model, torch_dtype=torch.float16, device_map="cpu", trust_remote_code=True,
    )
    peft_model = PeftModel.from_pretrained(base, str(adapter_dir))
    merged = peft_model.merge_and_unload()

    merged_dir = MERGED / adapter_dir.name
    merged_dir.mkdir(parents=True, exist_ok=True)
    merged.save_pretrained(str(merged_dir), safe_serialization=True)
    AutoTokenizer.from_pretrained(base_model, trust_remote_code=True).save_pretrained(str(merged_dir))
    log(f"merged model at {merged_dir}")
    return merged_dir


def convert_to_gguf(merged_dir, quant="q4_k_m"):
    """Convert HF model to GGUF via llama.cpp's convert.py."""
    GGUF_OUT.mkdir(parents=True, exist_ok=True)
    out = GGUF_OUT / f"{merged_dir.name}.{quant}.gguf"

    # Try several known locations for llama.cpp's convert.py
    candidates = [
        "llama.cpp/convert.py",
        os.path.expanduser("~/llama.cpp/convert.py"),
        "C:/llama.cpp/convert.py",
        "C:/Users/Admin/llama.cpp/convert.py",
    ]
    script = None
    for c in candidates:
        if os.path.exists(c):
            script = c
            break
    if not script:
        log("WARNING: llama.cpp convert.py not found in standard locations.")
        log("  install with:  git clone https://github.com/ggerganov/llama.cpp && pip install -r llama.cpp/requirements.txt")
        log("  then re-run with --convert-only or pass --llama-cpp /path/to/llama.cpp/convert.py")
        return None
    cmd = [sys.executable, script, str(merged_dir), "--outfile", str(out), "--outtype", quant]
    log("running:", " ".join(cmd))
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        log("convert failed:", r.stderr[:500])
        return None
    log(f"gguf at {out}")
    return out


def ollama_import(gguf_path, name=PURPCLAW_OLLAMA_NAME):
    """Create an Ollama model from a GGUF file."""
    if not gguf_path or not Path(gguf_path).exists():
        log(f"gguf not found: {gguf_path}")
        return False
    modelfile = gguf_path.parent / f"{gguf_path.stem}.Modelfile"
    modelfile.write_text(
        f"FROM {gguf_path}\n\n"
        "PARAMETER temperature 0.2\n"
        "PARAMETER num_ctx 4096\n"
        "SYSTEM \"You are Quill, the PURPCLAW runtime assistant. "
        "You manage 30+ services, run kernel jobs, fine-tune models overnight, "
        "and keep the lights on. Be direct, terse, technical.\"\n"
    )
    log(f"creating ollama model {name}…")
    r = subprocess.run(["ollama", "create", name, "-f", str(modelfile)],
                       capture_output=True, text=True)
    if r.returncode != 0:
        log("ollama create failed:", r.stderr[:500])
        return False
    log(f"✓ ollama model '{name}' created. try: ollama run {name}")
    return True


def update_env_model(name=PURPCLAW_OLLAMA_NAME):
    """Set LLM_MODEL in .env so the runtime picks up the new model."""
    env_path = Path("E:/god folder/02_ACTIVE_PROJECTS/PURPCLAW/.env")
    if not env_path.exists():
        log(f"  .env not found at {env_path}")
        return False
    txt = env_path.read_text()
    new_line = f"LLM_MODEL={name}"
    if re.search(r'^LLM_MODEL=.*$', txt, re.M):
        txt = re.sub(r'^LLM_MODEL=.*$', new_line, txt, flags=re.M)
    else:
        txt += f"\n{new_line}\n"
    env_path.write_text(txt)
    log(f"✓ .env updated: LLM_MODEL={name}")
    return True


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--base", default=DEFAULT_BASE,
                   help=f"HF base model (default: {DEFAULT_BASE})")
    p.add_argument("--epochs", type=float, default=DEFAULT_TRAIN_CONFIG["num_train_epochs"])
    p.add_argument("--batch-size", type=int, default=None)
    p.add_argument("--min-examples", type=int, default=10,
                   help="minimum number of training examples to proceed")
    p.add_argument("--skip-export", action="store_true",
                   help="stop after training, skip merge/gguf/ollama")
    p.add_argument("--skip-merge", action="store_true",
                   help="skip merge step, just save adapter")
    p.add_argument("--quant", default="q4_k_m",
                   help="GGUF quantization (default: q4_k_m)")
    p.add_argument("--ollama-name", default=PURPCLAW_OLLAMA_NAME)
    p.add_argument("--dry-run", action="store_true",
                   help="show plan, don't actually train")
    p.add_argument("--personal-dataset", default=None,
                   help="path to personal training dataset (ChatML JSON)")
    p.add_argument("--merge", action="store_true",
                   help="merge LoRA into base model after training")
    args = p.parse_args()

    log("=" * 60)
    log("PURPCLAW LoRA fine-tuning pipeline")
    if args.personal_dataset:
        log(f"  MODE: PERSONAL — training on your corrections")
    log("=" * 60)
    log(f"  base model : {args.base}")
    log(f"  epochs     : {args.epochs}")
    log(f"  batch size : {args.batch_size or DEFAULT_TRAIN_CONFIG['per_device_train_batch_size']}")
    log(f"  quant      : {args.quant}")
    log(f"  ollama name: {args.ollama_name}")
    if args.personal_dataset:
        log(f"  dataset    : {args.personal_dataset}")
    log("")

    if args.personal_dataset:
        examples = load_personal_dataset(args.personal_dataset)
    else:
        examples = load_training_ndjson()
    examples = maybe_filter_trajectories(examples)
    if len(examples) < args.min_examples:
        log(f"ERROR: only {len(examples)} examples; need at least {args.min_examples}.")
        log("  run the runtime for a while to accumulate trajectories,")
        log("  then re-run this script.")
        sys.exit(2)

    if args.dry_run:
        log("dry-run — exiting before training")
        return

    ADAPTERS.mkdir(parents=True, exist_ok=True)
    MERGED.mkdir(parents=True, exist_ok=True)
    GGUF_OUT.mkdir(parents=True, exist_ok=True)

    adapter_dir, _ = train(args.base, examples, args)
    if args.skip_export or args.skip_merge:
        log("done (training only)")
        return

    merged_dir = merge(adapter_dir, args.base)
    gguf = convert_to_gguf(merged_dir, quant=args.quant)
    if gguf and ollama_import(gguf, name=args.ollama_name):
        update_env_model(args.ollama_name)
        log("=" * 60)
        log("✓ pipeline complete")
        log(f"  adapter : {adapter_dir}")
        log(f"  merged  : {merged_dir}")
        log(f"  gguf    : {gguf}")
        log(f"  ollama  : {args.ollama_name}")
        log("  next run : pm2 restart purpclaw-api")
        log("=" * 60)


if __name__ == "__main__":
    main()
